wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718995526.784577
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
gan_version:
  desc: null
  value: CWGAN
generator_version:
  desc: null
  value: 4
discriminator_version:
  desc: null
  value: 3
random_seed:
  desc: null
  value: 40
avail_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 16
image_size:
  desc: null
  value: 28
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.0005
betas:
  desc: null
  value:
  - 0.0
  - 0.9
gp_lambda:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 20
epoch_start_g_train:
  desc: null
  value: 0
discriminator_train_freq:
  desc: null
  value: 5
latent_dim:
  desc: null
  value: 15
generator_img_w:
  desc: null
  value: 16
generator_upsamp_size:
  desc: null
  value: 128
input_channels:
  desc: null
  value: 1
discriminator_conv_size:
  desc: null
  value: 32
discriminator_linear_size:
  desc: null
  value: 128
linear_dropout:
  desc: null
  value: 0.2
conv_dropout:
  desc: null
  value: 0.2
root_path:
  desc: null
  value: /home/nteo/projects/def-douglas/nteo/cosmo_project
model_name:
  desc: null
  value: CWGAN-g4-d3-bn1-bs5-sn1e4-is28-ts40-lr0005-ld15-gw16-gu128-dc32-dl128
